import {
  Modal,
  Box,
  Typography,
  IconButton,
  CircularProgress,
  Button,
  Tooltip,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { useEffect, useState } from 'react';
import api from '../utils/axios';
import copy from 'copy-to-clipboard';

export default function AiSummaryModal({
  open,
  onClose,
}: {
  open: boolean;
  onClose(): void;
}) {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;

    async function fetchSummary() {
      setLoading(true);
      setError(null);
      setSummary(null);
      try {
        const res = await api.post('/api/expense/ai/analyze', { query: 'all' });
        setSummary(
          res.data?.insight ||
            res.data?.insightText ||
            res.data?.insight ||
            'No summary returned.'
        );
      } catch (err: any) {
        console.error('AI summarize error', err);
        setError(
          err?.response?.data?.error ||
            err?.response?.data?.message ||
            err?.message ||
            'Failed to get summary'
        );
      } finally {
        setLoading(false);
      }
    }

    fetchSummary();
  }, [open]);

  const handleCopy = () => {
    if (summary) {
      copy(summary);
    }
  };

  return (
    <Modal open={open} onClose={onClose}>
      <Box
        sx={(theme) => ({
          width: 680,
          maxWidth: '95%',
          maxHeight: '80vh',
          overflowY: 'auto',
          p: 3,
          bgcolor: 'background.paper',
          color: 'text.primary',
          mx: 'auto',
          mt: '6vh',
          borderRadius: 2,
          boxShadow: 24,
          position: 'relative',
        })}
      >
        <IconButton
          onClick={onClose}
          sx={{
            position: 'absolute',
            right: 8,
            top: 8,
            color: 'text.secondary',
          }}
          size='large'
          aria-label='close'
        >
          <CloseIcon />
        </IconButton>

        <Typography variant='h6' gutterBottom>
          AI Expense Summary
        </Typography>

        <Typography variant='body2' color='text.secondary' sx={{ mb: 2 }}>
          This summary is generated by the integrated Gemini AI model. It
          analyses your recent expenses and gives quick insights.
        </Typography>

        {loading && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, my: 4 }}>
            <CircularProgress />
            <Typography>Analysing your expenses — hang tight...</Typography>
          </Box>
        )}

        {error && (
          <Box sx={{ my: 2 }}>
            <Typography color='error'>Error: {error}</Typography>
            <Button
              sx={{ mt: 1 }}
              variant='outlined'
              onClick={() => window.location.reload()}
            >
              Retry (refresh)
            </Button>
          </Box>
        )}

        {!loading && summary && (
          <Box sx={{ my: 1 }}>
            <Box
              sx={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <Typography variant='subtitle1'>Summary</Typography>
              <Box>
                <Tooltip title='Copy summary'>
                  <IconButton onClick={handleCopy} size='small'>
                    <ContentCopyIcon />
                  </IconButton>
                </Tooltip>
              </Box>
            </Box>

            <Box
              sx={{
                mt: 1,
                p: 2,
                borderRadius: 1,
                bgcolor: 'background.default',
                color: 'text.primary',
                whiteSpace: 'pre-wrap',
                fontFamily: 'inherit',
              }}
            >
              <Typography variant='body1'>{summary}</Typography>
            </Box>
          </Box>
        )}

        {!loading && !summary && !error && (
          <Typography color='text.secondary'>No summary available.</Typography>
        )}
      </Box>
    </Modal>
  );
}
